### PR TITLE
Setup handler callbacks for most BB interrupts

### PR DESCRIPTION
**Pull request by Thar0**
Some interrupt causes are still unhandled since it's still unclear to me how they should be acknowledged.

### CODE REVIEW

**Comment by rasky** [comment]
Should we maybe keep the “BB” prefix convention for these symbols that are mixed with N64 ones? For instance `register_BB_FLASH_handler`

**Comment by Thar0** [comment]
Added prefixes

**Comment by rasky** [comment]
You need a rebase here; this conflicts with another PR we merged where we moved all docs to header files

**Comment by Thar0** [comment]
I'm not sure there is a conflict? My branch was based on dc3b17f9ccf6058d3a516685bd31eaf44d399b86 which already incorporates ff7420adf2d92b51d42867e2e625d0accbd07901

**Pull request merged**
