### PR TITLE
separate versions from build and add math libs

### PR DESCRIPTION
**Pull request by jopadan**
- add support for different versions and file types and move it to config
- add math lib dependencies
-  add clean up scripts

### CODE REVIEW

**Comment by rasky** [comment]
Hi thanks for the PR.

This PR is also changing many flags in the configure scripts. Would you mind commenting on why each change was made and how it is useful in the context of libdragon?

**Comment by anacierdem** [comment]
I am also currently working on an automated docker build via GitHub Actions. It will be generating and uploading a docker image for the toolchain and will verify that the toolchain is building properly whenever toolchain script changes. So it might be nice to wait for it so that this can be tested against it without someone manually testing it, which is very risky as creating a clean environment is finicky.

**Comment by rasky** [comment]
Hi @jopadan, the CI is up and running. If you want to still work on this, would you please rebase this branch on the current trunk, and then provide explanations of all compilation flags that you're changing? Thanks!

**Comment by rasky** [comment]
Closing for lack of feedback. Can reopen if still interested in pushing this.

**Pull request closed without merging**
