### PR TITLE
Adding restart_timer and new_timer_stopped functions

### PR DESCRIPTION
**Pull request by stefanmielke**
These functions allowed me to add a new timer that was stopped and that could be restarted later as callbacks to actions.

### CODE REVIEW

**Comment by anacierdem** [comment]
Instead of splitting the initializer into two, I'd suggest having a new flag (e.g `TF_ENABLED`) causing `__proc_timers` to skip processing it. With the current implementation `new_timer_stopped` will create a dangling timer if not explicitly handled. Also adding a new flag will make testing new functionality much easier.

**Review by anacierdem — CHANGES_REQUESTED** [review]
Instead of splitting the initializer into two, I'd suggest having a new flag (e.g `TF_ENABLED`) causing `__proc_timers` to skip processing it. With the current implementation `new_timer_stopped` will create a dangling timer if not explicitly handled. Also adding a new flag will make testing new functionality much easier. Also @rasky is very accustomed to the implementation, and might have an opinion on this.

**Comment by rasky** [comment]
Yeah I'd probably use a flag as well to set the timer as stopped, but I'd check that in `new_timer` and simply avoid registering the timer. `restart_timer` looks fine,

**Comment by anacierdem** [comment]
What should it mean to restart a timer multiple times? Should we really register a few?

**Comment by rasky** [comment]
Well it should probably be a nop but at the same time we have the same behavior in start_timer today. So I guess restart_timer is coherent with start_timer

**Comment by stefanmielke** [comment]
Made the changes to new_timer_stopped. With this change we could also include a "pause/resume" functionality later.

**Comment by anacierdem** [comment]
An additional test case would be really nice. It would also make the usage more visible.

**Comment by stefanmielke** [comment]
Fixed a few problems and added a couple tests. Also made a few changes to tests that were having issues to make them pass correctly.

**Comment by rasky** [comment]
Thanks, looks fine to me!

**Pull request merged**
