### PR TITLE
Fix comments on controller.h (analog stick state)

### PR DESCRIPTION
**Pull request by TheFakeMontyOnTheRun**
The previous comment was, most likely, a copy-paste mistake. Even if my changes don't get approved, just by calling attention to this spot is enough for me :)

### CODE REVIEW

**Review by anacierdem — APPROVED** [review]
Will merge once ci is green :)

**Comment by snacchus** [comment]
> Will merge once ci is green :)

This can be merged straight to trunk tbh

**Comment by anacierdem** [comment]
Ah didn't realize it was targeting ogl. I will update the target

**Comment by anacierdem** [comment]
@TheFakeMontyOnTheRun if you can have a version targeting trunk, we can merge it right away. I have changed the target but your branch is based on opengl :)

**Comment by TheFakeMontyOnTheRun** [comment]
Sorry, forgot to fix this :)
Ironically, I first created it for `trunk`, but then noticed it, deleted and created for `opengl`. Will now create it for `trunk` again.

**Pull request closed without merging**
