### PR TITLE
Two small fixes to n64.mk for RSP builds

### PR DESCRIPTION
**Pull request by rasky**

### CODE REVIEW

**Comment by anacierdem** [comment]
I think this was not onto the latest trunk. Can you verify you are in sync and all the changes are intended?

**Comment by rasky** [comment]
Looking at the diff, it looks OK to me. What changes seem unintended?

**Comment by anacierdem** [comment]
There are diffs on `audio.c` on the lines you have inteoduced the AI h/w fix. They seem to be reverted. Maybe there is something wrong with the GitHub app if that was not intended.

**Comment by anacierdem** [comment]
Commits look ok must be something weird with the app. I will check on web later.

**Pull request merged**
